---
title: try-catch-finally
---

Конструкция try-catch-finally является частью обработки исключений.

Состоит из трех блоков:

- **try**: блок может содержать одну или несколько инструкций. Если внутри блока try происходит исключение, оно перехватывается, и выполнение программы переходит к соответствующему блоку catch.

- **catch**: блок содержит код, который выполняется только в случае возникновения исключения. Можно указать несколько блоков catch или использовать один общий блок catch.

- **finally**: блок содержит код, который будет выполняться независимо от того, возникло исключение или нет. Блок finally полезен, когда нужно гарантировать выполнение определенных действий. Даже если произошло исключение и оно было перехвачено в блоке catch, код в блоке finally все равно будет выполнен.
